// Rezept-Datenbank – Mengen in "ingredients" sind PRO PERSON PRO PORTION.
// tags: 'lowcarb' | 'protein' | 'kalorienarm' | 'schnell' (alle Tags sind vollständig manuell gepflegt –
// es gibt KEINE automatische Ableitung von 'schnell' aus time <= 30, das muss pro Rezept selbst gesetzt werden)
// nutrition: { kcal, protein, carbs, fat } – ebenfalls PRO PORTION, protein/carbs/fat in Gramm.

export const RECIPES = [
  // ---------------- FLEISCH ----------------
  {
    id: "hf1", category: "fleisch", title: "Hähnchen-Gemüse-Pfanne mit Reis",
    time: 30, freezer: true, tags: ["protein", "schnell", "kalorienarm"],
    nutrition: { kcal: 445, protein: 43, carbs: 60, fat: 3 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "Reis", amount: 60, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Hähnchen in Streifen schneiden, scharf anbraten.",
      "Gemüse zugeben, 5–6 Min mitbraten.",
      "Mit Sojasauce und Knoblauch abschmecken, mit Reis servieren.",
    ],
  },
  {
    id: "hf2", category: "fleisch", title: "Rindfleisch-Chili mit Kidneybohnen",
    time: 55, freezer: true, tags: ["protein"],
    nutrition: { kcal: 500, protein: 35, carbs: 35, fat: 24 },
    ingredients: [
      { name: "Rinderhack", amount: 140, unit: "g" },
      { name: "Kidneybohnen", amount: 80, unit: "g" },
      { name: "Tomaten, gehackt", amount: 150, unit: "g" },
      { name: "Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Mais", amount: 40, unit: "g" },
      { name: "Chilipulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel andünsten, Hack scharf anbraten.",
      "Tomaten, Bohnen und Mais zugeben, würzen.",
      "20–25 Min köcheln lassen, gelegentlich umrühren.",
    ],
  },
  {
    id: "hf3", category: "fleisch", title: "Putengeschnetzeltes mit Süßkartoffel",
    time: 35, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 360, protein: 37, carbs: 34, fat: 7 },
    ingredients: [
      { name: "Putenbrust", amount: 150, unit: "g" },
      { name: "Süßkartoffel", amount: 150, unit: "g" },
      { name: "Zucchini", amount: 80, unit: "g" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Süßkartoffel würfeln, im Ofen oder in der Pfanne garen.",
      "Pute in Streifen anbraten, Zucchini zugeben.",
      "Mit Sahne und Paprikapulver ablöschen, kurz einkochen.",
    ],
  },
  {
    id: "hf4", category: "fleisch", title: "Gyros-Bowl mit Tzatziki",
    time: 40, freezer: false, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 450, protein: 42, carbs: 55, fat: 8 },
    ingredients: [
      { name: "Schweinegeschnetzeltes", amount: 150, unit: "g" },
      { name: "Gyrosgewürz", amount: 1, unit: "TL" },
      { name: "Bulgur", amount: 60, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Joghurt", amount: 60, unit: "g" },
      { name: "Cherrytomaten", amount: 60, unit: "g" },
    ],
    steps: [
      "Bulgur nach Packungsanweisung quellen lassen.",
      "Fleisch mit Gyrosgewürz scharf anbraten.",
      "Gurke fein reiben, mit Joghurt zu Tzatziki verrühren.",
      "Alles in einer Bowl anrichten.",
    ],
  },
  {
    id: "hf5", category: "fleisch", title: "Hackfleisch-Zucchini-Auflauf",
    time: 50, freezer: true, tags: ["lowcarb", "protein", "kalorienarm"],
    nutrition: { kcal: 440, protein: 34, carbs: 10, fat: 29 },
    ingredients: [
      { name: "Rinderhack", amount: 130, unit: "g" },
      { name: "Zucchini", amount: 200, unit: "g" },
      { name: "Tomatensauce", amount: 80, unit: "g" },
      { name: "Mozzarella", amount: 40, unit: "g" },
      { name: "Oregano", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Hack anbraten, mit Tomatensauce und Oregano mischen.",
      "Zucchini in Scheiben schichten, Hackmasse darauf verteilen.",
      "Mit Mozzarella belegen, 20 Min bei 200°C backen.",
    ],
  },
  {
    id: "hf6", category: "fleisch", title: "Asiatisches Rind mit Glasnudeln",
    time: 25, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 390, protein: 31, carbs: 50, fat: 6 },
    ingredients: [
      { name: "Rinderstreifen", amount: 140, unit: "g" },
      { name: "Glasnudeln", amount: 50, unit: "g" },
      { name: "Karotte", amount: 0.5, unit: "Stk" },
      { name: "Frühlingszwiebel", amount: 1, unit: "Stk" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Ingwer", amount: 1, unit: "TL" },
    ],
    steps: [
      "Glasnudeln in heißem Wasser einweichen.",
      "Rind scharf anbraten, Karotte und Ingwer zugeben.",
      "Nudeln und Sojasauce unterheben, mit Frühlingszwiebel servieren.",
    ],
  },
  {
    id: "hf7", category: "fleisch", title: "Schweinefilet mit Kartoffelpüree und grünen Bohnen",
    time: 45, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 405, protein: 40, carbs: 44, fat: 8 },
    ingredients: [
      { name: "Schweinefilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "grüne Bohnen", amount: 120, unit: "g" },
      { name: "Butter", amount: 1, unit: "TL" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Mit Milch und Butter zu Püree stampfen.",
      "Schweinefilet in Medaillons schneiden, scharf anbraten, 6–8 Min braten.",
      "Bohnen in Salzwasser 8 Min garen, abgießen.",
      "Alles zusammen anrichten.",
    ],
  },
  {
    id: "hf8", category: "fleisch", title: "Hähnchen-Curry mit Kokosmilch und Spinat",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 570, protein: 44, carbs: 46, fat: 24 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "Kokosmilch", amount: 100, unit: "ml" },
      { name: "Spinat", amount: 100, unit: "g" },
      { name: "Currypaste", amount: 1, unit: "TL" },
      { name: "Reis", amount: 50, unit: "g" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Hähnchen würfeln und in einer Pfanne anbraten.",
      "Currypaste einrühren, kurz mitrösten.",
      "Kokosmilch angießen, 8–10 Min köcheln lassen.",
      "Spinat unterrühren, zusammenfallen lassen, mit Reis servieren.",
    ],
  },
  {
    id: "hf9", category: "fleisch", title: "Lammhack-Pita mit Joghurtsauce",
    time: 25, freezer: false, tags: ["schnell", "protein"],
    nutrition: { kcal: 490, protein: 28, carbs: 26, fat: 29 },
    ingredients: [
      { name: "Lammhack", amount: 130, unit: "g" },
      { name: "Fladenbrot", amount: 0.5, unit: "Stk" },
      { name: "Joghurt", amount: 50, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Minze", amount: 3, unit: "g" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Lammhack mit Kreuzkümmel würzen und krümelig anbraten.",
      "Gurke fein würfeln, mit Joghurt und Minze zu einer Sauce verrühren.",
      "Fladenbrot kurz erwärmen.",
      "Lammhack und Joghurtsauce ins Fladenbrot füllen oder daneben servieren.",
    ],
  },
  {
    id: "hf10", category: "fleisch", title: "Hähnchen-Fajita-Bowl mit schwarzen Bohnen und Mais",
    time: 25, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 540, protein: 55, carbs: 35, fat: 20 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "schwarze Bohnen", amount: 80, unit: "g" },
      { name: "Mais", amount: 50, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "rote Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Hähnchen in Streifen schneiden, mit Paprikapulver würzen.",
      "In einer Pfanne scharf anbraten, Paprika und Zwiebel zugeben.",
      "Bohnen und Mais unterheben, kurz erhitzen.",
      "Mit Limettensaft beträufeln, in einer Bowl anrichten.",
    ],
  },
  {
    id: "hf11", category: "fleisch", title: "Schweinefilet-Medaillons mit Rotkohl und Kartoffelpüree",
    time: 55, freezer: true, tags: ["protein"],
    nutrition: { kcal: 535, protein: 46, carbs: 64, fat: 11 },
    ingredients: [
      { name: "Schweinefilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Rotkohl", amount: 150, unit: "g" },
      { name: "Apfel", amount: 0.3, unit: "Stk" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Rotkohl mit Apfelstückchen in einem Topf erwärmen, 10 Min köcheln.",
      "Schweinefilet salzen, pfeffern, rundum scharf anbraten.",
      "Im Ofen bei 180°C ca. 15–18 Min fertig garen.",
      "Kartoffeln mit Milch und Butter zu Püree stampfen, mit Filet und Rotkohl servieren.",
    ],
  },
  {
    id: "hf12", category: "fleisch", title: "Putenbolognese mit Vollkornnudeln",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 595, protein: 50, carbs: 55, fat: 19 },
    ingredients: [
      { name: "Putenhack", amount: 130, unit: "g" },
      { name: "Vollkornnudeln", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Karotte", amount: 50, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Parmesan", amount: 10, unit: "g" },
      { name: "Oregano", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel und Karotte fein würfeln, andünsten.",
      "Putenhack zugeben, krümelig anbraten.",
      "Tomaten und Oregano zugeben, 15–20 Min köcheln lassen.",
      "Nudeln nach Packungsanweisung kochen.",
      "Bolognese über die Nudeln geben, mit Parmesan bestreuen.",
    ],
  },
  {
    id: "hf13", category: "fleisch", title: "Honig-Senf-Hähnchenschenkel mit Ofenkartoffeln",
    time: 45, freezer: true, tags: ["protein"],
    nutrition: { kcal: 590, protein: 44, carbs: 49, fat: 24 },
    ingredients: [
      { name: "Hähnchenschenkel", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Honig", amount: 1, unit: "TL" },
      { name: "Senf", amount: 1, unit: "EL" },
      { name: "Olivenöl", amount: 0.5, unit: "EL" },
      { name: "Rosmarin", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Kartoffeln in Spalten schneiden, mit etwas Öl vermengen.",
      "Honig, Senf und Rosmarin verrühren, Hähnchenschenkel damit bestreichen.",
      "Kartoffeln und Hähnchen auf ein Blech geben.",
      "35–40 Min bei 200°C backen, bis alles goldbraun ist.",
    ],
  },
  {
    id: "hf14", category: "fleisch", title: "Rinder-Stroganoff mit Reis",
    time: 30, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 485, protein: 47, carbs: 25, fat: 22 },
    ingredients: [
      { name: "Rinderstreifen", amount: 140, unit: "g" },
      { name: "Champignons", amount: 100, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Sahne (leicht)", amount: 3, unit: "EL" },
      { name: "Senf", amount: 1, unit: "TL" },
      { name: "Reis", amount: 60, unit: "g" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Zwiebel und Champignons in einer Pfanne andünsten.",
      "Rinderstreifen zugeben, scharf anbraten.",
      "Sahne, Senf und Paprikapulver einrühren, kurz köcheln lassen.",
      "Mit Reis servieren.",
    ],
  },
  {
    id: "hf15", category: "fleisch", title: "Chorizo-Kichererbsen-Pfanne mit Paprika",
    time: 20, freezer: false, tags: ["schnell", "protein"],
    nutrition: { kcal: 545, protein: 29, carbs: 53, fat: 25 },
    ingredients: [
      { name: "Chorizo", amount: 60, unit: "g" },
      { name: "Kichererbsen", amount: 150, unit: "g" },
      { name: "Paprika", amount: 1, unit: "Stk" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Chorizo in Scheiben schneiden, in einer Pfanne knusprig anbraten.",
      "Zwiebel, Knoblauch und Paprika zugeben, mitbraten.",
      "Kichererbsen zugeben, mit Paprikapulver würzen.",
      "8–10 Min braten, bis alles heiß und leicht karamellisiert ist.",
    ],
  },

  {
    id: "hf16", category: "fleisch", title: "Hähnchen-Schawarma-Bowl mit Couscous und Hummus",
    time: 25, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 530, protein: 45, carbs: 49, fat: 17 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "Couscous", amount: 50, unit: "g" },
      { name: "Hummus", amount: 40, unit: "g" },
      { name: "Kirschtomaten", amount: 60, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Zitronensaft", amount: 1, unit: "EL" },
      { name: "Schawarma-Gewürz", amount: 1, unit: "TL" },
    ],
    steps: [
      "Hähnchenbrust in Streifen schneiden und mit Schawarma-Gewürz würzen.",
      "Couscous mit kochendem Wasser übergießen, 5 Min quellen lassen.",
      "Hähnchen in Olivenöl scharf anbraten, bis es gar ist.",
      "Gurke und Kirschtomaten klein schneiden.",
      "Couscous, Hähnchen, Gemüse und Hummus in einer Bowl anrichten, mit Zitronensaft beträufeln.",
    ],
  },
  {
    id: "hf17", category: "fleisch", title: "Schweinekotelett mit Kürbis-Kartoffel-Ofengemüse",
    time: 40, freezer: true, tags: ["protein"],
    nutrition: { kcal: 480, protein: 34, carbs: 27, fat: 27 },
    ingredients: [
      { name: "Schweinekotelett", amount: 150, unit: "g" },
      { name: "Kürbis", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 100, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Rosmarin", amount: 0.5, unit: "TL" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
    ],
    steps: [
      "Kürbis und Kartoffeln in Stücke schneiden, mit Öl vermengen.",
      "20 Min bei 200°C vorbacken.",
      "Schweinekotelett mit Rosmarin und Knoblauch würzen, in einer Pfanne von beiden Seiten scharf anbraten.",
      "Gemüse und Kotelett zusammen weitere 8–10 Min im Ofen fertig garen.",
    ],
  },
  {
    id: "hf18", category: "fleisch", title: "Rinderhack-Köfte mit Bulgur-Tomatensalat",
    time: 30, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 535, protein: 31, carbs: 47, fat: 25 },
    ingredients: [
      { name: "Rinderhack", amount: 130, unit: "g" },
      { name: "Bulgur", amount: 50, unit: "g" },
      { name: "Tomaten, gehackt", amount: 100, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Petersilie", amount: 5, unit: "g" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
      { name: "Zitronensaft", amount: 1, unit: "EL" },
      { name: "Olivenöl", amount: 1, unit: "TL" },
    ],
    steps: [
      "Bulgur mit kochendem Wasser übergießen, 10 Min quellen lassen.",
      "Rinderhack mit fein gehackter Zwiebel, Kreuzkümmel und Petersilie vermengen, zu Köfte formen.",
      "Köfte in Olivenöl rundum braun anbraten, ca. 8 Min.",
      "Bulgur mit Tomaten und Zitronensaft zu einem Salat mischen.",
      "Köfte auf dem Bulgursalat anrichten.",
    ],
  },
  {
    id: "hf19", category: "fleisch", title: "Kassler mit Sauerkraut und Kartoffelstampf",
    time: 45, freezer: true, tags: ["protein"],
    nutrition: { kcal: 510, protein: 37, carbs: 42, fat: 20 },
    ingredients: [
      { name: "Kassler", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Sauerkraut", amount: 150, unit: "g" },
      { name: "Senf", amount: 1, unit: "TL" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Mit Milch und Butter zu Stampf verarbeiten.",
      "Sauerkraut in einem Topf mit etwas Wasser 15 Min erwärmen.",
      "Kassler in Scheiben schneiden, in einer Pfanne kurz erhitzen.",
      "Mit Kartoffelstampf, Sauerkraut und einem Klecks Senf servieren.",
    ],
  },
  {
    id: "hf20", category: "fleisch", title: "Weißer-Bohnen-Eintopf mit Speck und Möhren",
    time: 55, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 420, protein: 16, carbs: 53, fat: 15 },
    ingredients: [
      { name: "Speck", amount: 25, unit: "g" },
      { name: "weiße Bohnen", amount: 130, unit: "g" },
      { name: "Karotte", amount: 80, unit: "g" },
      { name: "Kartoffeln", amount: 80, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Gemüsebrühe", amount: 300, unit: "ml" },
      { name: "Petersilie", amount: 5, unit: "g" },
    ],
    steps: [
      "Speck in Würfel schneiden und in einem Topf auslassen.",
      "Zwiebel zugeben und andünsten.",
      "Karotte und Kartoffeln würfeln, mit der Brühe auffüllen.",
      "25–30 Min köcheln, bis das Gemüse weich ist.",
      "Bohnen zugeben, kurz mit erhitzen, mit Petersilie bestreuen.",
    ],
  },

  // ---------------- FISCH ----------------
  {
    id: "fi1", category: "fisch", title: "Lachs mit Ofengemüse",
    time: 35, freezer: true, tags: ["protein", "lowcarb"],
    nutrition: { kcal: 500, protein: 34, carbs: 16, fat: 34 },
    ingredients: [
      { name: "Lachsfilet", amount: 150, unit: "g" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Karotte", amount: 80, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Gemüse mit Öl vermengen, 15 Min bei 200°C vorbacken.",
      "Lachs dazugeben, weitere 12–15 Min backen.",
      "Mit Zitrone beträufeln.",
    ],
  },
  {
    id: "fi2", category: "fisch", title: "Garnelen-Zoodles mit Knoblauch",
    time: 20, freezer: false, tags: ["lowcarb", "schnell", "kalorienarm", "protein"],
    nutrition: { kcal: 270, protein: 26, carbs: 8, fat: 16 },
    ingredients: [
      { name: "Garnelen", amount: 130, unit: "g" },
      { name: "Zucchini (zu Zoodles)", amount: 200, unit: "g" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
      { name: "Chiliflocken", amount: 1, unit: "Prise" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Zucchini zu Nudeln spiralisieren.",
      "Garnelen mit Knoblauch und Chili kurz anbraten.",
      "Zoodles 2 Min mitschwenken, sofort servieren.",
    ],
  },
  {
    id: "fi3", category: "fisch", title: "Thunfisch-Bowl mit Quinoa",
    time: 25, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 490, protein: 46, carbs: 47, fat: 13 },
    ingredients: [
      { name: "Thunfisch (im eigenen Saft)", amount: 120, unit: "g" },
      { name: "Quinoa", amount: 60, unit: "g" },
      { name: "Avocado", amount: 0.25, unit: "Stk" },
      { name: "Edamame", amount: 50, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "TL" },
    ],
    steps: [
      "Quinoa kochen und abkühlen lassen.",
      "Edamame kurz blanchieren.",
      "Alle Zutaten in einer Bowl anrichten, mit Sojasauce beträufeln.",
    ],
  },
  {
    id: "fi4", category: "fisch", title: "Kabeljau-Curry mit Kokosmilch",
    time: 40, freezer: true, tags: ["protein"],
    nutrition: { kcal: 560, protein: 35, carbs: 55, fat: 23 },
    ingredients: [
      { name: "Kabeljaufilet", amount: 150, unit: "g" },
      { name: "Kokosmilch", amount: 100, unit: "ml" },
      { name: "Currypaste", amount: 1, unit: "TL" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Reis", amount: 60, unit: "g" },
    ],
    steps: [
      "Currypaste in Kokosmilch anrühren, aufkochen.",
      "Paprika zugeben, 5 Min köcheln.",
      "Fisch zugeben, 8–10 Min ziehen lassen. Mit Reis servieren.",
    ],
  },
  {
    id: "fi5", category: "fisch", title: "Fischfrikadellen mit Gurkensalat",
    time: 45, freezer: true, tags: ["protein", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 260, protein: 34, carbs: 20, fat: 5 },
    ingredients: [
      { name: "Weißfischfilet", amount: 150, unit: "g" },
      { name: "Ei", amount: 0.5, unit: "Stk" },
      { name: "Semmelbrösel", amount: 20, unit: "g" },
      { name: "Gurke", amount: 0.5, unit: "Stk" },
      { name: "Dill", amount: 1, unit: "TL" },
    ],
    steps: [
      "Fisch fein hacken, mit Ei und Semmelbröseln vermengen.",
      "Frikadellen formen und goldbraun braten.",
      "Gurke in Scheiben hobeln, mit Dill anmachen.",
    ],
  },
  {
    id: "fi6", category: "fisch", title: "Räucherlachs-Linsen-Salat",
    time: 15, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 280, protein: 30, carbs: 28, fat: 5 },
    ingredients: [
      { name: "Räucherlachs", amount: 100, unit: "g" },
      { name: "Linsen (gekocht)", amount: 120, unit: "g" },
      { name: "Rucola", amount: 30, unit: "g" },
      { name: "Kirschtomaten", amount: 60, unit: "g" },
      { name: "Zitronensaft", amount: 1, unit: "EL" },
    ],
    steps: [
      "Linsen mit Rucola und Tomaten mischen.",
      "Lachs in Streifen darauf anrichten.",
      "Mit Zitronensaft beträufeln.",
    ],
  },
  {
    id: "fi7", category: "fisch", title: "Seelachs-Auflauf mit Kartoffeln und Lauch",
    time: 45, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 445, protein: 39, carbs: 39, fat: 15 },
    ingredients: [
      { name: "Seelachsfilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 150, unit: "g" },
      { name: "Lauch", amount: 80, unit: "g" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Käse (gerieben)", amount: 30, unit: "g" },
    ],
    steps: [
      "Kartoffeln in Scheiben schneiden, 10 Min vorkochen.",
      "Lauch in Ringe schneiden, kurz andünsten.",
      "Kartoffeln, Lauch und Fisch in eine Auflaufform schichten.",
      "Mit Sahne beträufeln, mit Käse bestreuen.",
      "20 Min bei 200°C überbacken.",
    ],
  },
  {
    id: "fi8", category: "fisch", title: "Fisch-Tacos mit Rotkohlsalat",
    time: 25, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 290, protein: 29, carbs: 35, fat: 3 },
    ingredients: [
      { name: "Weißfischfilet", amount: 130, unit: "g" },
      { name: "Maistortilla", amount: 2, unit: "Stk" },
      { name: "Rotkohl", amount: 80, unit: "g" },
      { name: "Joghurt", amount: 30, unit: "g" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Fisch mit Paprikapulver würzen, in der Pfanne braten und grob zerteilen.",
      "Rotkohl fein hobeln, mit Limettensaft vermengen.",
      "Tortillas kurz erwärmen.",
      "Tortillas mit Fisch, Rotkohlsalat und einem Klecks Joghurt füllen.",
    ],
  },
  {
    id: "fi9", category: "fisch", title: "Forelle mit Mandeln und grünem Spargel",
    time: 30, freezer: false, tags: ["schnell", "protein", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 380, protein: 38, carbs: 10, fat: 22 },
    ingredients: [
      { name: "Forellenfilet", amount: 150, unit: "g" },
      { name: "grüner Spargel", amount: 150, unit: "g" },
      { name: "Mandelblättchen", amount: 15, unit: "g" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Spargel waschen, holzige Enden entfernen.",
      "Forelle salzen, in Butter braten, ca. 4 Min pro Seite.",
      "Spargel parallel in etwas Wasser oder Butter 6–8 Min garen.",
      "Mandelblättchen kurz in einer Pfanne rösten.",
      "Forelle mit Spargel anrichten, mit Mandeln und Zitrone servieren.",
    ],
  },
  {
    id: "fi10", category: "fisch", title: "Lachs-Pasta mit Spinat und Zitrone",
    time: 25, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 585, protein: 38, carbs: 51, fat: 24 },
    ingredients: [
      { name: "Lachsfilet", amount: 130, unit: "g" },
      { name: "Vollkornnudeln", amount: 70, unit: "g" },
      { name: "Spinat", amount: 80, unit: "g" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
    ],
    steps: [
      "Nudeln nach Packungsanweisung kochen.",
      "Lachs würfeln, mit Knoblauch in einer Pfanne kurz anbraten.",
      "Spinat zugeben und zusammenfallen lassen.",
      "Sahne einrühren, mit Zitronensaft abschmecken.",
      "Mit den Nudeln vermengen und servieren.",
    ],
  },
  {
    id: "fi11", category: "fisch", title: "Zanderfilet mit Kartoffelstampf und Gurkensalat",
    time: 40, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 365, protein: 34, carbs: 39, fat: 7 },
    ingredients: [
      { name: "Zanderfilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Gurke", amount: 0.5, unit: "Stk" },
      { name: "Dill", amount: 1, unit: "TL" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Mit Milch und Butter zu Stampf verarbeiten.",
      "Gurke in dünne Scheiben hobeln, mit Dill vermengen.",
      "Zanderfilet salzen, in einer Pfanne von beiden Seiten goldbraun braten.",
      "Mit Kartoffelstampf und Gurkensalat servieren.",
    ],
  },
  {
    id: "fi12", category: "fisch", title: "Garnelen-Pad-Thai",
    time: 30, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 555, protein: 46, carbs: 67, fat: 11 },
    ingredients: [
      { name: "Garnelen", amount: 130, unit: "g" },
      { name: "Reisnudeln", amount: 70, unit: "g" },
      { name: "Ei", amount: 1, unit: "Stk" },
      { name: "Karotte", amount: 60, unit: "g" },
      { name: "Erdnüsse, gehackt", amount: 10, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
    ],
    steps: [
      "Reisnudeln in heißem Wasser einweichen, bis sie weich sind.",
      "Karotte in dünne Streifen schneiden.",
      "Garnelen im Wok scharf anbraten, Karotte zugeben.",
      "Ei verquirlen, zugeben und stocken lassen, Nudeln und Sojasauce unterheben.",
      "Mit Erdnüssen und Limettensaft servieren.",
    ],
  },
  {
    id: "fi13", category: "fisch", title: "Mediterraner Fisch-Eintopf mit Kartoffeln und Tomaten",
    time: 50, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 445, protein: 34, carbs: 44, fat: 16 },
    ingredients: [
      { name: "Weißfischfilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 150, unit: "g" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Fenchel", amount: 100, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
    ],
    steps: [
      "Zwiebel, Knoblauch und Fenchel in Olivenöl andünsten.",
      "Kartoffeln würfeln, zugeben und kurz mitdünsten.",
      "Tomaten zugeben, mit Wasser auffüllen und 25 Min köcheln, bis die Kartoffeln weich sind.",
      "Fisch in Stücke schneiden, zugeben und 8–10 Min ziehen lassen.",
      "Mit Salz und Pfeffer abschmecken.",
    ],
  },
  {
    id: "fi14", category: "fisch", title: "Sesam-Thunfisch-Steak mit Wok-Gemüse",
    time: 20, freezer: false, tags: ["protein", "lowcarb", "kalorienarm", "schnell"],
    nutrition: { kcal: 365, protein: 39, carbs: 12, fat: 17 },
    ingredients: [
      { name: "Thunfischsteak (frisch)", amount: 150, unit: "g" },
      { name: "Sesam", amount: 1, unit: "EL" },
      { name: "Pak Choi", amount: 150, unit: "g" },
      { name: "Karotte", amount: 60, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Sesamöl", amount: 1, unit: "TL" },
      { name: "Ingwer", amount: 1, unit: "TL" },
    ],
    steps: [
      "Thunfischsteak rundum in Sesam wenden.",
      "In einer heißen Pfanne von jeder Seite 1–2 Min scharf anbraten, beiseitestellen.",
      "Pak Choi und Karotte in Sesamöl mit Ingwer anbraten.",
      "Mit Sojasauce ablöschen, kurz durchschwenken.",
      "Thunfisch in Scheiben schneiden und auf dem Gemüse anrichten.",
    ],
  },
  {
    id: "fi15", category: "fisch", title: "Matjes mit Bratkartoffeln und Apfel-Zwiebel",
    time: 35, freezer: false, tags: ["protein"],
    nutrition: { kcal: 580, protein: 25, carbs: 51, fat: 32 },
    ingredients: [
      { name: "Matjesfilet", amount: 120, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Apfel", amount: 0.5, unit: "Stk" },
      { name: "Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Schnittlauch", amount: 3, unit: "g" },
    ],
    steps: [
      "Kartoffeln schälen, in Scheiben schneiden und in Salzwasser 10 Min vorkochen.",
      "In einer Pfanne mit Olivenöl goldbraun braten.",
      "Zwiebel und Apfel in dünne Streifen schneiden, in den letzten Minuten mitbraten.",
      "Matjesfilets in Stücke schneiden.",
      "Bratkartoffeln mit Matjes anrichten, mit Schnittlauch bestreuen.",
    ],
  },

  {
    id: "fi16", category: "fisch", title: "Rotbarschfilet mit Kartoffelstampf und Spinat",
    time: 35, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 375, protein: 35, carbs: 40, fat: 8 },
    ingredients: [
      { name: "Rotbarschfilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Spinat", amount: 100, unit: "g" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Mit Milch und Butter zu Stampf verarbeiten.",
      "Rotbarschfilet salzen, in einer Pfanne von beiden Seiten 3–4 Min braten.",
      "Spinat kurz zusammenfallen lassen.",
      "Alles zusammen anrichten, mit Zitrone beträufeln.",
    ],
  },
  {
    id: "fi17", category: "fisch", title: "Miesmuscheln in Weißwein-Sud mit Baguette",
    time: 35, freezer: false, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 405, protein: 25, carbs: 44, fat: 9 },
    ingredients: [
      { name: "Miesmuscheln", amount: 400, unit: "g" },
      { name: "Weißwein", amount: 50, unit: "ml" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Baguette", amount: 60, unit: "g" },
      { name: "Petersilie", amount: 5, unit: "g" },
    ],
    steps: [
      "Miesmuscheln gründlich putzen, geöffnete Exemplare aussortieren.",
      "Zwiebel und Knoblauch in einem großen Topf andünsten.",
      "Mit Weißwein ablöschen, Muscheln zugeben und zugedeckt 6–8 Min garen, bis sie sich geöffnet haben.",
      "Sahne einrühren, mit Petersilie bestreuen.",
      "Mit Baguette servieren, geschlossen gebliebene Muscheln aussortieren.",
    ],
  },
  {
    id: "fi18", category: "fisch", title: "Lachs-Poke-Bowl mit Reis, Edamame und Avocado",
    time: 20, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 580, protein: 36, carbs: 50, fat: 28 },
    ingredients: [
      { name: "Lachsfilet", amount: 120, unit: "g" },
      { name: "Reis", amount: 50, unit: "g" },
      { name: "Edamame", amount: 50, unit: "g" },
      { name: "Avocado", amount: 0.25, unit: "Stk" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Sesam", amount: 1, unit: "TL" },
    ],
    steps: [
      "Reis kochen und abkühlen lassen.",
      "Lachsfilet (sushitauglich) in Würfel schneiden.",
      "Edamame kurz blanchieren, Avocado in Scheiben schneiden.",
      "Alles auf dem Reis anrichten, mit Sojasauce und Sesam bestreuen.",
    ],
  },
  {
    id: "fi19", category: "fisch", title: "Scholle Müllerin Art mit Petersilienkartoffeln",
    time: 30, freezer: false, tags: ["protein", "kalorienarm", "schnell"],
    nutrition: { kcal: 420, protein: 31, carbs: 43, fat: 13 },
    ingredients: [
      { name: "Schollenfilet", amount: 150, unit: "g" },
      { name: "Mehl", amount: 1, unit: "EL" },
      { name: "Butter", amount: 1, unit: "EL" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Petersilie", amount: 5, unit: "g" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser 15 Min garen.",
      "Schollenfilet leicht in Mehl wenden.",
      "In Butter von beiden Seiten je 2–3 Min goldbraun braten.",
      "Kartoffeln mit Petersilie schwenken.",
      "Fisch mit Kartoffeln anrichten, mit Zitrone beträufeln.",
    ],
  },
  {
    id: "fi20", category: "fisch", title: "Thunfisch-Nizza-Salat mit Ei und grünen Bohnen",
    time: 25, freezer: false, tags: ["protein", "kalorienarm", "schnell"],
    nutrition: { kcal: 415, protein: 36, carbs: 27, fat: 19 },
    ingredients: [
      { name: "Thunfisch (im eigenen Saft)", amount: 100, unit: "g" },
      { name: "Kartoffeln", amount: 100, unit: "g" },
      { name: "grüne Bohnen", amount: 80, unit: "g" },
      { name: "Ei", amount: 1, unit: "Stk" },
      { name: "Kirschtomaten", amount: 60, unit: "g" },
      { name: "Oliven", amount: 15, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Zitronensaft", amount: 1, unit: "EL" },
    ],
    steps: [
      "Kartoffeln in Salzwasser weich kochen, Ei hart kochen.",
      "Grüne Bohnen 5–6 Min blanchieren.",
      "Kartoffeln und Ei in Scheiben schneiden.",
      "Alle Zutaten mit dem Thunfisch in einer Schüssel anrichten.",
      "Mit Olivenöl und Zitronensaft beträufeln.",
    ],
  },

  // ---------------- VEGETARISCH ----------------
  {
    id: "ve1", category: "vegetarisch", title: "Ofengemüse mit Halloumi",
    time: 35, freezer: false, tags: ["lowcarb", "protein"],
    nutrition: { kcal: 500, protein: 25, carbs: 15, fat: 40 },
    ingredients: [
      { name: "Halloumi", amount: 100, unit: "g" },
      { name: "Zucchini", amount: 100, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "rote Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Gemüse würfeln, mit Öl vermengen, 20 Min bei 200°C rösten.",
      "Halloumi in Scheiben anbraten.",
      "Alles zusammen servieren.",
    ],
  },
  {
    id: "ve2", category: "vegetarisch", title: "Linsen-Dal mit Fladenbrot",
    time: 40, freezer: true, tags: ["protein"],
    nutrition: { kcal: 565, protein: 25, carbs: 77, fat: 20 },
    ingredients: [
      { name: "rote Linsen", amount: 80, unit: "g" },
      { name: "Kokosmilch", amount: 80, unit: "ml" },
      { name: "Curry-Gewürzmischung", amount: 1, unit: "TL" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Fladenbrot", amount: 0.5, unit: "Stk" },
    ],
    steps: [
      "Zwiebel andünsten, Gewürze kurz mitrösten.",
      "Linsen und Kokosmilch zugeben, mit Wasser auffüllen.",
      "20 Min köcheln, bis Linsen weich sind.",
    ],
  },
  {
    id: "ve3", category: "vegetarisch", title: "Caprese-Nudelsalat",
    time: 20, freezer: false, tags: ["schnell"],
    nutrition: { kcal: 535, protein: 21, carbs: 49, fat: 27 },
    ingredients: [
      { name: "Vollkornnudeln", amount: 70, unit: "g" },
      { name: "Kirschtomaten", amount: 100, unit: "g" },
      { name: "Mozzarella", amount: 60, unit: "g" },
      { name: "Basilikum", amount: 5, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Nudeln kochen, abkühlen lassen.",
      "Tomaten halbieren, Mozzarella würfeln.",
      "Alles mit Öl und Basilikum vermengen.",
    ],
  },
  {
    id: "ve4", category: "vegetarisch", title: "Gemüse-Frittata",
    time: 30, freezer: true, tags: ["lowcarb", "protein", "kalorienarm", "schnell"],
    nutrition: { kcal: 340, protein: 26, carbs: 7, fat: 24 },
    ingredients: [
      { name: "Eier", amount: 3, unit: "Stk" },
      { name: "Spinat", amount: 60, unit: "g" },
      { name: "Feta", amount: 40, unit: "g" },
      { name: "Cherrytomaten", amount: 50, unit: "g" },
    ],
    steps: [
      "Eier verquirlen, mit Gemüse und Feta mischen.",
      "In eine Pfanne geben, bei mittlerer Hitze stocken lassen.",
      "10 Min im Ofen bei 180°C fertig backen.",
    ],
  },
  {
    id: "ve5", category: "vegetarisch", title: "Kichererbsen-Curry",
    time: 30, freezer: true, tags: ["schnell"],
    nutrition: { kcal: 550, protein: 17, carbs: 77, fat: 20 },
    ingredients: [
      { name: "Kichererbsen", amount: 120, unit: "g" },
      { name: "Kokosmilch", amount: 80, unit: "ml" },
      { name: "Tomaten, gehackt", amount: 100, unit: "g" },
      { name: "Currypulver", amount: 1, unit: "TL" },
      { name: "Reis", amount: 60, unit: "g" },
    ],
    steps: [
      "Currypulver kurz anrösten.",
      "Tomaten, Kokosmilch und Kichererbsen zugeben.",
      "15 Min köcheln, mit Reis servieren.",
    ],
  },
  {
    id: "ve6", category: "vegetarisch", title: "Quinoa-Bowl mit Feta und Granatapfel",
    time: 25, freezer: false, tags: ["schnell", "kalorienarm"],
    nutrition: { kcal: 395, protein: 17, carbs: 50, fat: 15 },
    ingredients: [
      { name: "Quinoa", amount: 60, unit: "g" },
      { name: "Feta", amount: 50, unit: "g" },
      { name: "Granatapfelkerne", amount: 30, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Minze", amount: 3, unit: "g" },
    ],
    steps: [
      "Quinoa kochen und abkühlen lassen.",
      "Gurke würfeln, mit Feta und Granatapfel mischen.",
      "Mit Minze bestreuen.",
    ],
  },
  {
    id: "ve7", category: "vegetarisch", title: "Pilz-Risotto mit Parmesan",
    time: 40, freezer: false, tags: ["kalorienarm"],
    nutrition: { kcal: 380, protein: 16, carbs: 56, fat: 10 },
    ingredients: [
      { name: "Risottoreis", amount: 60, unit: "g" },
      { name: "Champignons", amount: 150, unit: "g" },
      { name: "Parmesan", amount: 20, unit: "g" },
      { name: "Gemüsebrühe", amount: 200, unit: "ml" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Butter", amount: 1, unit: "TL" },
    ],
    steps: [
      "Zwiebel fein würfeln und in Butter andünsten.",
      "Risottoreis zugeben, kurz mitrösten.",
      "Nach und nach heiße Brühe angießen, dabei ständig rühren, bis der Reis cremig ist (ca. 20 Min).",
      "Champignons separat anbraten und unterheben.",
      "Parmesan einrühren, mit Salz und Pfeffer abschmecken.",
    ],
  },
  {
    id: "ve8", category: "vegetarisch", title: "Shakshuka mit Feta",
    time: 25, freezer: false, tags: ["schnell", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 300, protein: 19, carbs: 18, fat: 17 },
    ingredients: [
      { name: "Eier", amount: 2, unit: "Stk" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Feta", amount: 30, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel und Paprika andünsten.",
      "Tomaten zugeben, mit Kreuzkümmel würzen, 10 Min köcheln.",
      "Mulden in die Sauce drücken, Eier hineingeben.",
      "Zugedeckt stocken lassen, bis das Eiweiß fest ist.",
      "Mit Feta bestreuen und servieren.",
    ],
  },
  {
    id: "ve9", category: "vegetarisch", title: "Gemüse-Chili sin Carne mit Käse",
    time: 40, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 340, protein: 20, carbs: 43, fat: 10 },
    ingredients: [
      { name: "Kidneybohnen", amount: 100, unit: "g" },
      { name: "Mais", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 150, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Käse (gerieben)", amount: 30, unit: "g" },
      { name: "Chilipulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Paprika würfeln, kurz andünsten.",
      "Tomaten, Bohnen und Mais zugeben.",
      "Mit Chilipulver würzen, 20 Min köcheln lassen.",
      "Mit Käse bestreut servieren.",
    ],
  },
  {
    id: "ve10", category: "vegetarisch", title: "Käsespätzle mit Röstzwiebeln und Blattsalat",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 585, protein: 26, carbs: 48, fat: 32 },
    ingredients: [
      { name: "Spätzle", amount: 150, unit: "g" },
      { name: "Käse (gerieben)", amount: 60, unit: "g" },
      { name: "Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Butter", amount: 1, unit: "EL" },
      { name: "Blattsalat", amount: 50, unit: "g" },
    ],
    steps: [
      "Spätzle nach Packungsanweisung kochen oder erhitzen.",
      "Zwiebel in Ringe schneiden, in Butter goldbraun und knusprig braten.",
      "Spätzle mit Käse in einer Pfanne vermengen, bei milder Hitze schmelzen lassen.",
      "Mit Röstzwiebeln bestreuen.",
      "Mit Blattsalat servieren.",
    ],
  },
  {
    id: "ve11", category: "vegetarisch", title: "Ofen-Süßkartoffel mit schwarzen Bohnen und Käse",
    time: 45, freezer: false, tags: ["protein"],
    nutrition: { kcal: 550, protein: 25, carbs: 72, fat: 19 },
    ingredients: [
      { name: "Süßkartoffel", amount: 200, unit: "g" },
      { name: "schwarze Bohnen", amount: 120, unit: "g" },
      { name: "Käse (gerieben)", amount: 40, unit: "g" },
      { name: "Saure Sahne", amount: 2, unit: "EL" },
      { name: "Frühlingszwiebel", amount: 1, unit: "Stk" },
    ],
    steps: [
      "Süßkartoffel waschen, einstechen und 40–45 Min bei 200°C backen, bis sie weich ist.",
      "Bohnen erwärmen.",
      "Süßkartoffel längs einschneiden, mit Bohnen und Käse füllen.",
      "Kurz überbacken, bis der Käse schmilzt.",
      "Mit saurer Sahne und Frühlingszwiebel garnieren.",
    ],
  },
  {
    id: "ve12", category: "vegetarisch", title: "Auberginen-Parmigiana mit Ciabatta",
    time: 50, freezer: true, tags: ["protein"],
    nutrition: { kcal: 645, protein: 30, carbs: 57, fat: 36 },
    ingredients: [
      { name: "Aubergine", amount: 250, unit: "g" },
      { name: "Tomatensauce", amount: 150, unit: "g" },
      { name: "Mozzarella", amount: 50, unit: "g" },
      { name: "Parmesan", amount: 15, unit: "g" },
      { name: "Ei", amount: 0.5, unit: "Stk" },
      { name: "Semmelbrösel", amount: 15, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Ciabatta", amount: 40, unit: "g" },
    ],
    steps: [
      "Aubergine in Scheiben schneiden, in Ei und Semmelbröseln wenden.",
      "In Olivenöl von beiden Seiten goldbraun braten.",
      "In einer Auflaufform abwechselnd mit Tomatensauce und Mozzarella schichten.",
      "Mit Parmesan bestreuen, 20 Min bei 200°C überbacken.",
      "Mit Ciabatta servieren.",
    ],
  },
  {
    id: "ve13", category: "vegetarisch", title: "Griechischer Halloumi-Salat",
    time: 15, freezer: false, tags: ["protein", "lowcarb", "schnell"],
    nutrition: { kcal: 545, protein: 28, carbs: 16, fat: 42 },
    ingredients: [
      { name: "Halloumi", amount: 100, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Kirschtomaten", amount: 100, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "rote Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Oliven", amount: 25, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Halloumi in Scheiben schneiden, in einer Pfanne ohne Öl goldbraun braten.",
      "Gurke, Kirschtomaten, Paprika und rote Zwiebel klein schneiden.",
      "Mit Oliven und Olivenöl vermengen.",
      "Gebratenen Halloumi auf dem Salat anrichten.",
    ],
  },
  {
    id: "ve14", category: "vegetarisch", title: "Gebratener Reis mit Ei und Gemüse",
    time: 20, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 525, protein: 27, carbs: 54, fat: 22 },
    ingredients: [
      { name: "Reis", amount: 50, unit: "g" },
      { name: "Eier", amount: 3, unit: "Stk" },
      { name: "Erbsen (TK)", amount: 50, unit: "g" },
      { name: "Karotte", amount: 50, unit: "g" },
      { name: "Frühlingszwiebel", amount: 1, unit: "Stk" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Sesamöl", amount: 1, unit: "TL" },
    ],
    steps: [
      "Reis kochen und am besten etwas auskühlen lassen.",
      "Karotte fein würfeln, in Sesamöl anbraten.",
      "Erbsen zugeben, kurz mitbraten.",
      "Reis dazugeben, verquirlte Eier darüber verteilen und unter Rühren stocken lassen.",
      "Mit Sojasauce und Frühlingszwiebel abschmecken.",
    ],
  },
  {
    id: "ve15", category: "vegetarisch", title: "Käse-Lauch-Suppe mit Croutons",
    time: 30, freezer: true, tags: ["kalorienarm", "schnell"],
    nutrition: { kcal: 405, protein: 13, carbs: 56, fat: 12 },
    ingredients: [
      { name: "Lauch", amount: 200, unit: "g" },
      { name: "Kartoffeln", amount: 100, unit: "g" },
      { name: "Gemüsebrühe", amount: 300, unit: "ml" },
      { name: "Käse (gerieben)", amount: 25, unit: "g" },
      { name: "Sahne (leicht)", amount: 1, unit: "EL" },
      { name: "Baguette", amount: 20, unit: "g" },
    ],
    steps: [
      "Lauch in Ringe schneiden, Kartoffeln würfeln.",
      "Beides in der Gemüsebrühe 15–18 Min weich köcheln.",
      "Käse und Sahne einrühren, bei Bedarf pürieren.",
      "Baguette würfeln und in einer Pfanne knusprig rösten.",
      "Suppe mit Croutons servieren.",
    ],
  },
  {
    id: "ve16", category: "vegetarisch", title: "Falafel-Bowl mit Hummus und Fladenbrot",
    time: 35, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 435, protein: 21, carbs: 56, fat: 16 },
    ingredients: [
      { name: "Kichererbsen", amount: 150, unit: "g" },
      { name: "Zwiebel", amount: 0.2, unit: "Stk" },
      { name: "Petersilie", amount: 5, unit: "g" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
      { name: "Olivenöl", amount: 1, unit: "TL" },
      { name: "Hummus", amount: 30, unit: "g" },
      { name: "Fladenbrot", amount: 0.3, unit: "Stk" },
      { name: "Weißkohl", amount: 60, unit: "g" },
      { name: "Joghurt", amount: 20, unit: "g" },
      { name: "Tahini", amount: 1, unit: "TL" },
    ],
    steps: [
      "Kichererbsen mit Zwiebel, Petersilie und Kreuzkümmel im Mixer grob pürieren.",
      "Kleine Bällchen formen, mit Olivenöl bestreichen und im Ofen bei 200°C 20 Min backen, dabei einmal wenden.",
      "Weißkohl fein hobeln, mit Joghurt zu einem Krautsalat mischen.",
      "Hummus mit Tahini verrühren.",
      "Falafel mit Krautsalat, Hummus und Fladenbrot anrichten.",
    ],
  },
  {
    id: "ve17", category: "vegetarisch", title: "Tofu-Gemüse-Pfanne süß-sauer mit Reis",
    time: 25, freezer: true, tags: ["kalorienarm", "schnell"],
    nutrition: { kcal: 435, protein: 18, carbs: 64, fat: 13 },
    ingredients: [
      { name: "Tofu", amount: 150, unit: "g" },
      { name: "Reis", amount: 50, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Ananas", amount: 50, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Tomatenmark", amount: 1, unit: "EL" },
      { name: "Honig", amount: 1, unit: "TL" },
      { name: "Speisestärke", amount: 1, unit: "TL" },
      { name: "Sesamöl", amount: 1, unit: "TL" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Tofu würfeln und in Sesamöl knusprig anbraten.",
      "Paprika in Streifen schneiden, mit Ananas zum Tofu geben und kurz mitbraten.",
      "Sojasauce, Tomatenmark, Honig und etwas Wasser verrühren, mit Speisestärke andicken.",
      "Sauce zum Gemüse geben, kurz köcheln, mit Reis servieren.",
    ],
  },
  {
    id: "ve18", category: "vegetarisch", title: "Linsenbolognese mit Vollkornnudeln",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 590, protein: 28, carbs: 87, fat: 16 },
    ingredients: [
      { name: "Linsen (gekocht)", amount: 150, unit: "g" },
      { name: "Vollkornnudeln", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Karotte", amount: 50, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Oregano", amount: 0.5, unit: "TL" },
      { name: "Parmesan", amount: 10, unit: "g" },
    ],
    steps: [
      "Zwiebel und Karotte fein würfeln, in Olivenöl andünsten.",
      "Linsen zugeben, kurz mitdünsten.",
      "Tomaten und Oregano zugeben, 15–20 Min köcheln lassen.",
      "Nudeln nach Packungsanweisung kochen.",
      "Bolognese über die Nudeln geben, mit Parmesan bestreuen.",
    ],
  },
  {
    id: "ve19", category: "vegetarisch", title: "Gefüllte Paprika mit Couscous und Feta",
    time: 45, freezer: true, tags: ["protein"],
    nutrition: { kcal: 560, protein: 25, carbs: 67, fat: 21 },
    ingredients: [
      { name: "Paprika", amount: 1, unit: "Stk" },
      { name: "Couscous", amount: 50, unit: "g" },
      { name: "Feta", amount: 50, unit: "g" },
      { name: "Tomaten, gehackt", amount: 80, unit: "g" },
      { name: "Zwiebel", amount: 0.2, unit: "Stk" },
      { name: "Olivenöl", amount: 0.5, unit: "EL" },
      { name: "Petersilie", amount: 5, unit: "g" },
      { name: "Kichererbsen", amount: 60, unit: "g" },
      { name: "Ei", amount: 0.5, unit: "Stk" },
    ],
    steps: [
      "Paprika halbieren, entkernen.",
      "Couscous mit kochendem Wasser übergießen, 5 Min quellen lassen.",
      "Zwiebel fein würfeln, mit Kichererbsen, Feta, Tomaten, Ei und Petersilie zum Couscous geben, vermengen.",
      "Paprikahälften mit der Masse füllen, mit Olivenöl beträufeln.",
      "25–30 Min bei 200°C backen.",
    ],
  },
  {
    id: "ve20", category: "vegetarisch", title: "Rote-Bete-Ziegenkäse-Salat mit Walnüssen",
    time: 15, freezer: false, tags: ["schnell", "kalorienarm"],
    nutrition: { kcal: 430, protein: 15, carbs: 26, fat: 31 },
    ingredients: [
      { name: "Rote Bete", amount: 150, unit: "g" },
      { name: "Ziegenkäse", amount: 50, unit: "g" },
      { name: "Walnüsse", amount: 15, unit: "g" },
      { name: "Rucola", amount: 30, unit: "g" },
      { name: "Honig", amount: 1, unit: "TL" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Balsamico-Essig", amount: 1, unit: "EL" },
    ],
    steps: [
      "Rote Bete in Scheiben oder Würfel schneiden.",
      "Rucola auf einem Teller verteilen, Rote Bete darauf anrichten.",
      "Ziegenkäse zerbröckeln, mit Walnüssen darüberstreuen.",
      "Honig, Olivenöl und Balsamico-Essig zu einem Dressing verrühren, über den Salat träufeln.",
    ],
  },
];
