// Rezept-Datenbank – Mengen in "ingredients" sind PRO PERSON PRO PORTION.
// tags: 'lowcarb' | 'protein' | 'kalorienarm' | 'schnell' (alle Tags sind vollständig manuell gepflegt –
// es gibt KEINE automatische Ableitung von 'schnell' aus time <= 30, das muss pro Rezept selbst gesetzt werden)
// nutrition: { kcal, protein, carbs, fat } – ebenfalls PRO PORTION, protein/carbs/fat in Gramm.

export const RECIPES = [
  // ---------------- FLEISCH ----------------
  {
    id: "hf1", category: "fleisch", title: "Hähnchen-Gemüse-Pfanne mit Reis",
    time: 30, freezer: true, tags: ["protein", "schnell", "kalorienarm"],
    nutrition: { kcal: 445, protein: 43, carbs: 60, fat: 3 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "Reis", amount: 60, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Hähnchen in Streifen schneiden, scharf anbraten.",
      "Gemüse zugeben, 5–6 Min mitbraten.",
      "Mit Sojasauce und Knoblauch abschmecken, mit Reis servieren.",
    ],
  },
  {
    id: "hf2", category: "fleisch", title: "Rindfleisch-Chili mit Kidneybohnen",
    time: 55, freezer: true, tags: ["protein"],
    nutrition: { kcal: 500, protein: 35, carbs: 35, fat: 24 },
    ingredients: [
      { name: "Rinderhack", amount: 140, unit: "g" },
      { name: "Kidneybohnen", amount: 80, unit: "g" },
      { name: "Tomaten, gehackt", amount: 150, unit: "g" },
      { name: "Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Mais", amount: 40, unit: "g" },
      { name: "Chilipulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel andünsten, Hack scharf anbraten.",
      "Tomaten, Bohnen und Mais zugeben, würzen.",
      "20–25 Min köcheln lassen, gelegentlich umrühren.",
    ],
  },
  {
    id: "hf3", category: "fleisch", title: "Putengeschnetzeltes mit Süßkartoffel",
    time: 35, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 360, protein: 37, carbs: 34, fat: 7 },
    ingredients: [
      { name: "Putenbrust", amount: 150, unit: "g" },
      { name: "Süßkartoffel", amount: 150, unit: "g" },
      { name: "Zucchini", amount: 80, unit: "g" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Süßkartoffel würfeln, im Ofen oder in der Pfanne garen.",
      "Pute in Streifen anbraten, Zucchini zugeben.",
      "Mit Sahne und Paprikapulver ablöschen, kurz einkochen.",
    ],
  },
  {
    id: "hf4", category: "fleisch", title: "Gyros-Bowl mit Tzatziki",
    time: 40, freezer: false, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 450, protein: 42, carbs: 55, fat: 8 },
    ingredients: [
      { name: "Schweinegeschnetzeltes", amount: 150, unit: "g" },
      { name: "Gyrosgewürz", amount: 1, unit: "TL" },
      { name: "Bulgur", amount: 60, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Joghurt", amount: 60, unit: "g" },
      { name: "Cherrytomaten", amount: 60, unit: "g" },
    ],
    steps: [
      "Bulgur nach Packungsanweisung quellen lassen.",
      "Fleisch mit Gyrosgewürz scharf anbraten.",
      "Gurke fein reiben, mit Joghurt zu Tzatziki verrühren.",
      "Alles in einer Bowl anrichten.",
    ],
  },
  {
    id: "hf5", category: "fleisch", title: "Hackfleisch-Zucchini-Auflauf",
    time: 50, freezer: true, tags: ["lowcarb", "protein", "kalorienarm"],
    nutrition: { kcal: 440, protein: 34, carbs: 10, fat: 29 },
    ingredients: [
      { name: "Rinderhack", amount: 130, unit: "g" },
      { name: "Zucchini", amount: 200, unit: "g" },
      { name: "Tomatensauce", amount: 80, unit: "g" },
      { name: "Mozzarella", amount: 40, unit: "g" },
      { name: "Oregano", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Hack anbraten, mit Tomatensauce und Oregano mischen.",
      "Zucchini in Scheiben schichten, Hackmasse darauf verteilen.",
      "Mit Mozzarella belegen, 20 Min bei 200°C backen.",
    ],
  },
  {
    id: "hf6", category: "fleisch", title: "Asiatisches Rind mit Glasnudeln",
    time: 25, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 390, protein: 31, carbs: 50, fat: 6 },
    ingredients: [
      { name: "Rinderstreifen", amount: 140, unit: "g" },
      { name: "Glasnudeln", amount: 50, unit: "g" },
      { name: "Karotte", amount: 0.5, unit: "Stk" },
      { name: "Frühlingszwiebel", amount: 1, unit: "Stk" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Ingwer", amount: 1, unit: "TL" },
    ],
    steps: [
      "Glasnudeln in heißem Wasser einweichen.",
      "Rind scharf anbraten, Karotte und Ingwer zugeben.",
      "Nudeln und Sojasauce unterheben, mit Frühlingszwiebel servieren.",
    ],
  },
  {
    id: "hf7", category: "fleisch", title: "Schweinefilet mit Kartoffelpüree und grünen Bohnen",
    time: 45, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 405, protein: 40, carbs: 44, fat: 8 },
    ingredients: [
      { name: "Schweinefilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "grüne Bohnen", amount: 120, unit: "g" },
      { name: "Butter", amount: 1, unit: "TL" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Mit Milch und Butter zu Püree stampfen.",
      "Schweinefilet in Medaillons schneiden, scharf anbraten, 6–8 Min braten.",
      "Bohnen in Salzwasser 8 Min garen, abgießen.",
      "Alles zusammen anrichten.",
    ],
  },
  {
    id: "hf8", category: "fleisch", title: "Hähnchen-Curry mit Kokosmilch und Spinat",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 570, protein: 44, carbs: 46, fat: 24 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "Kokosmilch", amount: 100, unit: "ml" },
      { name: "Spinat", amount: 100, unit: "g" },
      { name: "Currypaste", amount: 1, unit: "TL" },
      { name: "Reis", amount: 50, unit: "g" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Hähnchen würfeln und in einer Pfanne anbraten.",
      "Currypaste einrühren, kurz mitrösten.",
      "Kokosmilch angießen, 8–10 Min köcheln lassen.",
      "Spinat unterrühren, zusammenfallen lassen, mit Reis servieren.",
    ],
  },
  {
    id: "hf9", category: "fleisch", title: "Lammhack-Pita mit Joghurtsauce",
    time: 25, freezer: false, tags: ["schnell", "protein"],
    nutrition: { kcal: 490, protein: 28, carbs: 26, fat: 29 },
    ingredients: [
      { name: "Lammhack", amount: 130, unit: "g" },
      { name: "Fladenbrot", amount: 0.5, unit: "Stk" },
      { name: "Joghurt", amount: 50, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Minze", amount: 3, unit: "g" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Lammhack mit Kreuzkümmel würzen und krümelig anbraten.",
      "Gurke fein würfeln, mit Joghurt und Minze zu einer Sauce verrühren.",
      "Fladenbrot kurz erwärmen.",
      "Lammhack und Joghurtsauce ins Fladenbrot füllen oder daneben servieren.",
    ],
  },
  {
    id: "hf10", category: "fleisch", title: "Hähnchen-Fajita-Bowl mit schwarzen Bohnen und Mais",
    time: 25, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 540, protein: 55, carbs: 35, fat: 20 },
    ingredients: [
      { name: "Hähnchenbrust", amount: 150, unit: "g" },
      { name: "schwarze Bohnen", amount: 80, unit: "g" },
      { name: "Mais", amount: 50, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "rote Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Hähnchen in Streifen schneiden, mit Paprikapulver würzen.",
      "In einer Pfanne scharf anbraten, Paprika und Zwiebel zugeben.",
      "Bohnen und Mais unterheben, kurz erhitzen.",
      "Mit Limettensaft beträufeln, in einer Bowl anrichten.",
    ],
  },
  {
    id: "hf11", category: "fleisch", title: "Schweinefilet-Medaillons mit Rotkohl und Kartoffelpüree",
    time: 55, freezer: true, tags: ["protein"],
    nutrition: { kcal: 535, protein: 46, carbs: 64, fat: 11 },
    ingredients: [
      { name: "Schweinefilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Milch", amount: 30, unit: "ml" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Rotkohl", amount: 150, unit: "g" },
      { name: "Apfel", amount: 0.3, unit: "Stk" },
    ],
    steps: [
      "Kartoffeln schälen, würfeln und in Salzwasser weich kochen.",
      "Rotkohl mit Apfelstückchen in einem Topf erwärmen, 10 Min köcheln.",
      "Schweinefilet salzen, pfeffern, rundum scharf anbraten.",
      "Im Ofen bei 180°C ca. 15–18 Min fertig garen.",
      "Kartoffeln mit Milch und Butter zu Püree stampfen, mit Filet und Rotkohl servieren.",
    ],
  },
  {
    id: "hf12", category: "fleisch", title: "Putenbolognese mit Vollkornnudeln",
    time: 35, freezer: true, tags: ["protein"],
    nutrition: { kcal: 595, protein: 50, carbs: 55, fat: 19 },
    ingredients: [
      { name: "Putenhack", amount: 130, unit: "g" },
      { name: "Vollkornnudeln", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Karotte", amount: 50, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Parmesan", amount: 10, unit: "g" },
      { name: "Oregano", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel und Karotte fein würfeln, andünsten.",
      "Putenhack zugeben, krümelig anbraten.",
      "Tomaten und Oregano zugeben, 15–20 Min köcheln lassen.",
      "Nudeln nach Packungsanweisung kochen.",
      "Bolognese über die Nudeln geben, mit Parmesan bestreuen.",
    ],
  },
  {
    id: "hf13", category: "fleisch", title: "Honig-Senf-Hähnchenschenkel mit Ofenkartoffeln",
    time: 45, freezer: true, tags: ["protein"],
    nutrition: { kcal: 590, protein: 44, carbs: 49, fat: 24 },
    ingredients: [
      { name: "Hähnchenschenkel", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 200, unit: "g" },
      { name: "Honig", amount: 1, unit: "TL" },
      { name: "Senf", amount: 1, unit: "EL" },
      { name: "Olivenöl", amount: 0.5, unit: "EL" },
      { name: "Rosmarin", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Kartoffeln in Spalten schneiden, mit etwas Öl vermengen.",
      "Honig, Senf und Rosmarin verrühren, Hähnchenschenkel damit bestreichen.",
      "Kartoffeln und Hähnchen auf ein Blech geben.",
      "35–40 Min bei 200°C backen, bis alles goldbraun ist.",
    ],
  },
  {
    id: "hf14", category: "fleisch", title: "Rinder-Stroganoff mit Reis",
    time: 30, freezer: true, tags: ["protein", "schnell"],
    nutrition: { kcal: 485, protein: 47, carbs: 25, fat: 22 },
    ingredients: [
      { name: "Rinderstreifen", amount: 140, unit: "g" },
      { name: "Champignons", amount: 100, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Sahne (leicht)", amount: 3, unit: "EL" },
      { name: "Senf", amount: 1, unit: "TL" },
      { name: "Reis", amount: 60, unit: "g" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Zwiebel und Champignons in einer Pfanne andünsten.",
      "Rinderstreifen zugeben, scharf anbraten.",
      "Sahne, Senf und Paprikapulver einrühren, kurz köcheln lassen.",
      "Mit Reis servieren.",
    ],
  },
  {
    id: "hf15", category: "fleisch", title: "Chorizo-Kichererbsen-Pfanne mit Paprika",
    time: 20, freezer: false, tags: ["schnell", "protein"],
    nutrition: { kcal: 545, protein: 29, carbs: 53, fat: 25 },
    ingredients: [
      { name: "Chorizo", amount: 60, unit: "g" },
      { name: "Kichererbsen", amount: 150, unit: "g" },
      { name: "Paprika", amount: 1, unit: "Stk" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Chorizo in Scheiben schneiden, in einer Pfanne knusprig anbraten.",
      "Zwiebel, Knoblauch und Paprika zugeben, mitbraten.",
      "Kichererbsen zugeben, mit Paprikapulver würzen.",
      "8–10 Min braten, bis alles heiß und leicht karamellisiert ist.",
    ],
  },

  // ---------------- FISCH ----------------
  {
    id: "fi1", category: "fisch", title: "Lachs mit Ofengemüse",
    time: 35, freezer: true, tags: ["protein", "lowcarb"],
    nutrition: { kcal: 500, protein: 34, carbs: 16, fat: 34 },
    ingredients: [
      { name: "Lachsfilet", amount: 150, unit: "g" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Karotte", amount: 80, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Gemüse mit Öl vermengen, 15 Min bei 200°C vorbacken.",
      "Lachs dazugeben, weitere 12–15 Min backen.",
      "Mit Zitrone beträufeln.",
    ],
  },
  {
    id: "fi2", category: "fisch", title: "Garnelen-Zoodles mit Knoblauch",
    time: 20, freezer: false, tags: ["lowcarb", "schnell", "kalorienarm", "protein"],
    nutrition: { kcal: 270, protein: 26, carbs: 8, fat: 16 },
    ingredients: [
      { name: "Garnelen", amount: 130, unit: "g" },
      { name: "Zucchini (zu Zoodles)", amount: 200, unit: "g" },
      { name: "Knoblauch", amount: 1, unit: "Zehe" },
      { name: "Chiliflocken", amount: 1, unit: "Prise" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Zucchini zu Nudeln spiralisieren.",
      "Garnelen mit Knoblauch und Chili kurz anbraten.",
      "Zoodles 2 Min mitschwenken, sofort servieren.",
    ],
  },
  {
    id: "fi3", category: "fisch", title: "Thunfisch-Bowl mit Quinoa",
    time: 25, freezer: false, tags: ["protein", "schnell"],
    nutrition: { kcal: 490, protein: 46, carbs: 47, fat: 13 },
    ingredients: [
      { name: "Thunfisch (im eigenen Saft)", amount: 120, unit: "g" },
      { name: "Quinoa", amount: 60, unit: "g" },
      { name: "Avocado", amount: 0.25, unit: "Stk" },
      { name: "Edamame", amount: 50, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "TL" },
    ],
    steps: [
      "Quinoa kochen und abkühlen lassen.",
      "Edamame kurz blanchieren.",
      "Alle Zutaten in einer Bowl anrichten, mit Sojasauce beträufeln.",
    ],
  },
  {
    id: "fi4", category: "fisch", title: "Kabeljau-Curry mit Kokosmilch",
    time: 40, freezer: true, tags: ["protein"],
    nutrition: { kcal: 560, protein: 35, carbs: 55, fat: 23 },
    ingredients: [
      { name: "Kabeljaufilet", amount: 150, unit: "g" },
      { name: "Kokosmilch", amount: 100, unit: "ml" },
      { name: "Currypaste", amount: 1, unit: "TL" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Reis", amount: 60, unit: "g" },
    ],
    steps: [
      "Currypaste in Kokosmilch anrühren, aufkochen.",
      "Paprika zugeben, 5 Min köcheln.",
      "Fisch zugeben, 8–10 Min ziehen lassen. Mit Reis servieren.",
    ],
  },
  {
    id: "fi5", category: "fisch", title: "Fischfrikadellen mit Gurkensalat",
    time: 45, freezer: true, tags: ["protein", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 260, protein: 34, carbs: 20, fat: 5 },
    ingredients: [
      { name: "Weißfischfilet", amount: 150, unit: "g" },
      { name: "Ei", amount: 0.5, unit: "Stk" },
      { name: "Semmelbrösel", amount: 20, unit: "g" },
      { name: "Gurke", amount: 0.5, unit: "Stk" },
      { name: "Dill", amount: 1, unit: "TL" },
    ],
    steps: [
      "Fisch fein hacken, mit Ei und Semmelbröseln vermengen.",
      "Frikadellen formen und goldbraun braten.",
      "Gurke in Scheiben hobeln, mit Dill anmachen.",
    ],
  },
  {
    id: "fi6", category: "fisch", title: "Räucherlachs-Linsen-Salat",
    time: 15, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 280, protein: 30, carbs: 28, fat: 5 },
    ingredients: [
      { name: "Räucherlachs", amount: 100, unit: "g" },
      { name: "Linsen (gekocht)", amount: 120, unit: "g" },
      { name: "Rucola", amount: 30, unit: "g" },
      { name: "Kirschtomaten", amount: 60, unit: "g" },
      { name: "Zitronensaft", amount: 1, unit: "EL" },
    ],
    steps: [
      "Linsen mit Rucola und Tomaten mischen.",
      "Lachs in Streifen darauf anrichten.",
      "Mit Zitronensaft beträufeln.",
    ],
  },
  {
    id: "fi7", category: "fisch", title: "Seelachs-Auflauf mit Kartoffeln und Lauch",
    time: 45, freezer: true, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 445, protein: 39, carbs: 39, fat: 15 },
    ingredients: [
      { name: "Seelachsfilet", amount: 150, unit: "g" },
      { name: "Kartoffeln", amount: 150, unit: "g" },
      { name: "Lauch", amount: 80, unit: "g" },
      { name: "Sahne (leicht)", amount: 2, unit: "EL" },
      { name: "Käse (gerieben)", amount: 30, unit: "g" },
    ],
    steps: [
      "Kartoffeln in Scheiben schneiden, 10 Min vorkochen.",
      "Lauch in Ringe schneiden, kurz andünsten.",
      "Kartoffeln, Lauch und Fisch in eine Auflaufform schichten.",
      "Mit Sahne beträufeln, mit Käse bestreuen.",
      "20 Min bei 200°C überbacken.",
    ],
  },
  {
    id: "fi8", category: "fisch", title: "Fisch-Tacos mit Rotkohlsalat",
    time: 25, freezer: false, tags: ["schnell", "protein", "kalorienarm"],
    nutrition: { kcal: 290, protein: 29, carbs: 35, fat: 3 },
    ingredients: [
      { name: "Weißfischfilet", amount: 130, unit: "g" },
      { name: "Maistortilla", amount: 2, unit: "Stk" },
      { name: "Rotkohl", amount: 80, unit: "g" },
      { name: "Joghurt", amount: 30, unit: "g" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
      { name: "Paprikapulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Fisch mit Paprikapulver würzen, in der Pfanne braten und grob zerteilen.",
      "Rotkohl fein hobeln, mit Limettensaft vermengen.",
      "Tortillas kurz erwärmen.",
      "Tortillas mit Fisch, Rotkohlsalat und einem Klecks Joghurt füllen.",
    ],
  },
  {
    id: "fi9", category: "fisch", title: "Forelle mit Mandeln und grünem Spargel",
    time: 30, freezer: false, tags: ["schnell", "protein", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 380, protein: 38, carbs: 10, fat: 22 },
    ingredients: [
      { name: "Forellenfilet", amount: 150, unit: "g" },
      { name: "grüner Spargel", amount: 150, unit: "g" },
      { name: "Mandelblättchen", amount: 15, unit: "g" },
      { name: "Butter", amount: 1, unit: "TL" },
      { name: "Zitrone", amount: 0.25, unit: "Stk" },
    ],
    steps: [
      "Spargel waschen, holzige Enden entfernen.",
      "Forelle salzen, in Butter braten, ca. 4 Min pro Seite.",
      "Spargel parallel in etwas Wasser oder Butter 6–8 Min garen.",
      "Mandelblättchen kurz in einer Pfanne rösten.",
      "Forelle mit Spargel anrichten, mit Mandeln und Zitrone servieren.",
    ],
  },

  // ---------------- VEGETARISCH ----------------
  {
    id: "ve1", category: "vegetarisch", title: "Ofengemüse mit Halloumi",
    time: 35, freezer: false, tags: ["lowcarb", "protein"],
    nutrition: { kcal: 500, protein: 25, carbs: 15, fat: 40 },
    ingredients: [
      { name: "Halloumi", amount: 100, unit: "g" },
      { name: "Zucchini", amount: 100, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "rote Zwiebel", amount: 0.5, unit: "Stk" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Gemüse würfeln, mit Öl vermengen, 20 Min bei 200°C rösten.",
      "Halloumi in Scheiben anbraten.",
      "Alles zusammen servieren.",
    ],
  },
  {
    id: "ve2", category: "vegetarisch", title: "Linsen-Dal mit Fladenbrot",
    time: 40, freezer: true, tags: ["protein"],
    nutrition: { kcal: 565, protein: 25, carbs: 77, fat: 20 },
    ingredients: [
      { name: "rote Linsen", amount: 80, unit: "g" },
      { name: "Kokosmilch", amount: 80, unit: "ml" },
      { name: "Curry-Gewürzmischung", amount: 1, unit: "TL" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Fladenbrot", amount: 0.5, unit: "Stk" },
    ],
    steps: [
      "Zwiebel andünsten, Gewürze kurz mitrösten.",
      "Linsen und Kokosmilch zugeben, mit Wasser auffüllen.",
      "20 Min köcheln, bis Linsen weich sind.",
    ],
  },
  {
    id: "ve3", category: "vegetarisch", title: "Caprese-Nudelsalat",
    time: 20, freezer: false, tags: ["schnell"],
    nutrition: { kcal: 535, protein: 21, carbs: 49, fat: 27 },
    ingredients: [
      { name: "Vollkornnudeln", amount: 70, unit: "g" },
      { name: "Kirschtomaten", amount: 100, unit: "g" },
      { name: "Mozzarella", amount: 60, unit: "g" },
      { name: "Basilikum", amount: 5, unit: "g" },
      { name: "Olivenöl", amount: 1, unit: "EL" },
    ],
    steps: [
      "Nudeln kochen, abkühlen lassen.",
      "Tomaten halbieren, Mozzarella würfeln.",
      "Alles mit Öl und Basilikum vermengen.",
    ],
  },
  {
    id: "ve4", category: "vegetarisch", title: "Gemüse-Frittata",
    time: 30, freezer: true, tags: ["lowcarb", "protein", "kalorienarm", "schnell"],
    nutrition: { kcal: 340, protein: 26, carbs: 7, fat: 24 },
    ingredients: [
      { name: "Eier", amount: 3, unit: "Stk" },
      { name: "Spinat", amount: 60, unit: "g" },
      { name: "Feta", amount: 40, unit: "g" },
      { name: "Cherrytomaten", amount: 50, unit: "g" },
    ],
    steps: [
      "Eier verquirlen, mit Gemüse und Feta mischen.",
      "In eine Pfanne geben, bei mittlerer Hitze stocken lassen.",
      "10 Min im Ofen bei 180°C fertig backen.",
    ],
  },
  {
    id: "ve5", category: "vegetarisch", title: "Kichererbsen-Curry",
    time: 30, freezer: true, tags: ["schnell"],
    nutrition: { kcal: 550, protein: 17, carbs: 77, fat: 20 },
    ingredients: [
      { name: "Kichererbsen", amount: 120, unit: "g" },
      { name: "Kokosmilch", amount: 80, unit: "ml" },
      { name: "Tomaten, gehackt", amount: 100, unit: "g" },
      { name: "Currypulver", amount: 1, unit: "TL" },
      { name: "Reis", amount: 60, unit: "g" },
    ],
    steps: [
      "Currypulver kurz anrösten.",
      "Tomaten, Kokosmilch und Kichererbsen zugeben.",
      "15 Min köcheln, mit Reis servieren.",
    ],
  },
  {
    id: "ve6", category: "vegetarisch", title: "Quinoa-Bowl mit Feta und Granatapfel",
    time: 25, freezer: false, tags: ["schnell", "kalorienarm"],
    nutrition: { kcal: 395, protein: 17, carbs: 50, fat: 15 },
    ingredients: [
      { name: "Quinoa", amount: 60, unit: "g" },
      { name: "Feta", amount: 50, unit: "g" },
      { name: "Granatapfelkerne", amount: 30, unit: "g" },
      { name: "Gurke", amount: 0.3, unit: "Stk" },
      { name: "Minze", amount: 3, unit: "g" },
    ],
    steps: [
      "Quinoa kochen und abkühlen lassen.",
      "Gurke würfeln, mit Feta und Granatapfel mischen.",
      "Mit Minze bestreuen.",
    ],
  },
  {
    id: "ve7", category: "vegetarisch", title: "Pilz-Risotto mit Parmesan",
    time: 40, freezer: false, tags: ["kalorienarm"],
    nutrition: { kcal: 380, protein: 16, carbs: 56, fat: 10 },
    ingredients: [
      { name: "Risottoreis", amount: 60, unit: "g" },
      { name: "Champignons", amount: 150, unit: "g" },
      { name: "Parmesan", amount: 20, unit: "g" },
      { name: "Gemüsebrühe", amount: 200, unit: "ml" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Butter", amount: 1, unit: "TL" },
    ],
    steps: [
      "Zwiebel fein würfeln und in Butter andünsten.",
      "Risottoreis zugeben, kurz mitrösten.",
      "Nach und nach heiße Brühe angießen, dabei ständig rühren, bis der Reis cremig ist (ca. 20 Min).",
      "Champignons separat anbraten und unterheben.",
      "Parmesan einrühren, mit Salz und Pfeffer abschmecken.",
    ],
  },
  {
    id: "ve8", category: "vegetarisch", title: "Shakshuka mit Feta",
    time: 25, freezer: false, tags: ["schnell", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 300, protein: 19, carbs: 18, fat: 17 },
    ingredients: [
      { name: "Eier", amount: 2, unit: "Stk" },
      { name: "Tomaten, gehackt", amount: 200, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Feta", amount: 30, unit: "g" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Zwiebel und Paprika andünsten.",
      "Tomaten zugeben, mit Kreuzkümmel würzen, 10 Min köcheln.",
      "Mulden in die Sauce drücken, Eier hineingeben.",
      "Zugedeckt stocken lassen, bis das Eiweiß fest ist.",
      "Mit Feta bestreuen und servieren.",
    ],
  },
  {
    id: "ve9", category: "vegetarisch", title: "Gemüse-Chili sin Carne mit Käse",
    time: 40, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 340, protein: 20, carbs: 43, fat: 10 },
    ingredients: [
      { name: "Kidneybohnen", amount: 100, unit: "g" },
      { name: "Mais", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 150, unit: "g" },
      { name: "Paprika", amount: 0.5, unit: "Stk" },
      { name: "Käse (gerieben)", amount: 30, unit: "g" },
      { name: "Chilipulver", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Paprika würfeln, kurz andünsten.",
      "Tomaten, Bohnen und Mais zugeben.",
      "Mit Chilipulver würzen, 20 Min köcheln lassen.",
      "Mit Käse bestreut servieren.",
    ],
  },

  // ---------------- VEGAN ----------------
  {
    id: "va1", category: "vegan", title: "Buddha Bowl mit Tofu",
    time: 35, freezer: false, tags: ["protein", "kalorienarm"],
    nutrition: { kcal: 450, protein: 29, carbs: 43, fat: 21 },
    ingredients: [
      { name: "Tofu", amount: 120, unit: "g" },
      { name: "Süßkartoffel", amount: 100, unit: "g" },
      { name: "Grünkohl", amount: 50, unit: "g" },
      { name: "Tahin", amount: 1, unit: "EL" },
      { name: "Kichererbsen", amount: 60, unit: "g" },
    ],
    steps: [
      "Süßkartoffel würfeln und rösten, Kichererbsen mitrösten.",
      "Tofu würfeln und knusprig anbraten.",
      "Alles mit Grünkohl in einer Bowl anrichten, mit Tahin beträufeln.",
    ],
  },
  {
    id: "va2", category: "vegan", title: "Rote-Linsen-Suppe",
    time: 30, freezer: true, tags: ["protein", "kalorienarm", "schnell"],
    nutrition: { kcal: 395, protein: 25, carbs: 72, fat: 2 },
    ingredients: [
      { name: "rote Linsen", amount: 100, unit: "g" },
      { name: "Karotte", amount: 0.5, unit: "Stk" },
      { name: "Gemüsebrühe", amount: 300, unit: "ml" },
      { name: "Kreuzkümmel", amount: 0.5, unit: "TL" },
      { name: "Zwiebel", amount: 0.3, unit: "Stk" },
    ],
    steps: [
      "Zwiebel und Karotte andünsten.",
      "Linsen und Brühe zugeben, 20 Min köcheln.",
      "Mit Kreuzkümmel abschmecken, ggf. pürieren.",
    ],
  },
  {
    id: "va3", category: "vegan", title: "Sesam-Tofu-Nudeln",
    time: 25, freezer: false, tags: ["schnell", "protein"],
    nutrition: { kcal: 560, protein: 29, carbs: 55, fat: 26 },
    ingredients: [
      { name: "Tofu", amount: 120, unit: "g" },
      { name: "Eiernudeln (vegan)", amount: 70, unit: "g" },
      { name: "Pak Choi", amount: 80, unit: "g" },
      { name: "Sesamöl", amount: 1, unit: "EL" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
    ],
    steps: [
      "Nudeln kochen.",
      "Tofu würfeln und knusprig anbraten, Pak Choi mitdünsten.",
      "Mit Nudeln, Sesamöl und Sojasauce vermengen.",
    ],
  },
  {
    id: "va4", category: "vegan", title: "Gefüllte Paprika mit Bulgur",
    time: 45, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 360, protein: 16, carbs: 70, fat: 4 },
    ingredients: [
      { name: "Paprika", amount: 1, unit: "Stk" },
      { name: "Bulgur", amount: 50, unit: "g" },
      { name: "Kichererbsen", amount: 100, unit: "g" },
      { name: "Tomatensauce", amount: 60, unit: "g" },
      { name: "Petersilie", amount: 3, unit: "g" },
    ],
    steps: [
      "Bulgur quellen lassen, mit Kichererbsen und Tomatensauce mischen.",
      "Paprika halbieren, entkernen und füllen.",
      "25 Min bei 200°C backen.",
    ],
  },
  {
    id: "va5", category: "vegan", title: "Erdnuss-Gemüse-Wok",
    time: 20, freezer: false, tags: ["schnell", "lowcarb", "kalorienarm"],
    nutrition: { kcal: 310, protein: 23, carbs: 20, fat: 18 },
    ingredients: [
      { name: "Tofu", amount: 100, unit: "g" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Karotte", amount: 60, unit: "g" },
      { name: "Erdnussbutter", amount: 1, unit: "EL" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
    ],
    steps: [
      "Tofu anbraten, Gemüse zugeben und wokken.",
      "Erdnussbutter mit Sojasauce und etwas Wasser verrühren.",
      "Sauce unterheben, kurz einkochen lassen.",
    ],
  },
  {
    id: "va6", category: "vegan", title: "Weiße-Bohnen-Eintopf",
    time: 35, freezer: true, tags: ["kalorienarm"],
    nutrition: { kcal: 230, protein: 12, carbs: 43, fat: 1 },
    ingredients: [
      { name: "weiße Bohnen", amount: 120, unit: "g" },
      { name: "Lauch", amount: 60, unit: "g" },
      { name: "Karotte", amount: 60, unit: "g" },
      { name: "Tomaten, gehackt", amount: 100, unit: "g" },
      { name: "Thymian", amount: 0.5, unit: "TL" },
    ],
    steps: [
      "Lauch und Karotte andünsten.",
      "Bohnen und Tomaten zugeben, mit Wasser auffüllen.",
      "20 Min köcheln, mit Thymian würzen.",
    ],
  },
  {
    id: "va7", category: "vegan", title: "Falafel-Bowl mit Hummus",
    time: 35, freezer: false, tags: ["kalorienarm"],
    nutrition: { kcal: 395, protein: 16, carbs: 53, fat: 15 },
    ingredients: [
      { name: "Kichererbsen", amount: 100, unit: "g" },
      { name: "Hummus", amount: 50, unit: "g" },
      { name: "Bulgur", amount: 30, unit: "g" },
      { name: "Kirschtomaten", amount: 50, unit: "g" },
      { name: "Gurke", amount: 0.2, unit: "Stk" },
      { name: "Olivenöl", amount: 0.5, unit: "EL" },
    ],
    steps: [
      "Bulgur nach Packungsanweisung quellen lassen.",
      "Kichererbsen mit Gewürzen pürieren, zu Bällchen formen und goldbraun braten oder backen.",
      "Tomaten und Gurke würfeln, mit Öl anmachen.",
      "Bulgur, Falafel, Salat und Hummus in einer Bowl anrichten.",
    ],
  },
  {
    id: "va8", category: "vegan", title: "Teriyaki-Tempeh mit Reis",
    time: 30, freezer: true, tags: ["schnell", "protein"],
    nutrition: { kcal: 515, protein: 32, carbs: 70, fat: 14 },
    ingredients: [
      { name: "Tempeh", amount: 120, unit: "g" },
      { name: "Reis", amount: 60, unit: "g" },
      { name: "Brokkoli", amount: 100, unit: "g" },
      { name: "Sojasauce", amount: 1, unit: "EL" },
      { name: "Agavendicksaft", amount: 1, unit: "TL" },
      { name: "Ingwer", amount: 1, unit: "TL" },
    ],
    steps: [
      "Reis nach Packungsanweisung kochen.",
      "Tempeh würfeln und knusprig anbraten.",
      "Brokkoli kurz mitdünsten.",
      "Sojasauce, Agavendicksaft und Ingwer verrühren, zum Tempeh geben und kurz einkochen.",
      "Mit Reis servieren.",
    ],
  },
  {
    id: "va9", category: "vegan", title: "Schwarze-Bohnen-Bowl mit Mais und Avocado",
    time: 20, freezer: false, tags: ["schnell", "kalorienarm"],
    nutrition: { kcal: 350, protein: 17, carbs: 55, fat: 9 },
    ingredients: [
      { name: "schwarze Bohnen", amount: 150, unit: "g" },
      { name: "Mais", amount: 60, unit: "g" },
      { name: "Avocado", amount: 0.3, unit: "Stk" },
      { name: "Kirschtomaten", amount: 60, unit: "g" },
      { name: "Limette", amount: 0.5, unit: "Stk" },
      { name: "Koriander", amount: 3, unit: "g" },
    ],
    steps: [
      "Bohnen und Mais erwärmen oder direkt verwenden.",
      "Avocado in Scheiben schneiden, Tomaten halbieren.",
      "Alles in einer Bowl anrichten.",
      "Mit Limettensaft und Koriander abschmecken.",
    ],
  },
];
